-- AlterTable
ALTER TABLE "productHistory" ALTER COLUMN "totalpacket" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION;
